sudo: required

language: cpp
services:
  - docker

script:
  - mkdir apps
  - docker build . -f deploydocker/Dockerfile.winedeploy.ubuntu1804 -t wineappimage.ubuntu1804
  - docker run --rm -v $(pwd)/apps:/tmp/apps -ti wineappimage.ubuntu1804 cp Wine-x86_64.AppImage /tmp/apps/Wine-x86_64-ubuntu1804.AppImage
  - docker build . -f deploydocker/Dockerfile.winedeploy.archlatest -t wineappimage.archlatest
  - docker run --rm -v $(pwd)/apps:/tmp/apps -ti wineappimage.archlatest cp Wine-x86_64.AppImage /tmp/apps/Wine-x86_64-archlatest.AppImage

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh apps/*
